ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - before: if [[ -z "$experiment" ]]; then cd playground/; else cd playground/$experiment; fi
    command: nvm install 15.0.0 && npm install && npm start